### ISSUE TITLE
Authorization docs don't describe precedence/interaction of allow/deny

### ISSUE THREAD

**Issue by philpennock** [nats-io/nats.docs#21]
The docs on page:
    https://docs.nats.io/nats-server/configuration/securing_nats/authorization
don't describe how allow and deny lists interact: whether either changes implicit defaults, which takes precedence, etc.

**Comment by matthiashanel** [comment]
I had a similar thought and a while ago changed the doc to say:

The `permission` map provides additional properties for configuring a `permissions` map. Instead of providing a list of allowable subjects and optional queues, the `permission` map allows you to explicitly list those you want to`allow` or `deny`. Both lists can be provided. In case of overlap `deny` has priority.

Do you think this addresses this issue adequately?
