### ISSUE TITLE
Orphaned nats-concepts/acks.md

### ISSUE THREAD

**Issue by mihaitodor** [nats-io/nats.docs#344]
I can't seem to find any link to https://github.com/nats-io/nats.docs/blob/080861171b23d30c7181b4b5aebda688d78de697/nats-concepts/acks.md under https://docs.nats.io/nats-concepts/overview. Is this intentional?

**Comment by gcolliso** [comment]
@jnmoyne Do you know what happened to the nats-concepts/acks.md file? Should it be somewhere or did we move the information. It's not showing in the current docs version.

**Comment by jnmoyne** [comment]
Yes, it is intentional as that particular page pre-dates JetStream and the concept of using Acks yourself in your application code to create 'streams' is now outdated because you should be using JetStream instead (and specifically acknowledgements on some types of consumers). 

For example the page in question had this text in it:

> When you are publishing an event or data stream, one way to ensure message delivery is to turn it into a request-reply with > the concept of an acknowledgement message, or ACKs. In NATS an ACK can simply be an empty message, a message
> with no payload.

This is now outdated information because nowadays if you want to do a stream then you should use the JetStream functionalities rather than merely turning your publish into request-reply and try to re-invent JetStream.

The concepts section of the documentation now includes a JetStream sub-section where those acknowledgements are mentioned (https://docs.nats.io/nats-concepts/jetstream#consumer-acknowledgements). Note that JetStream also expands on the ack functionality (from what was available pre-JetStream and therefore from what was documented in concepts/acks.md) by introducing Nack and In progress types of acknowledgements.

**Comment by mihaitodor** [comment]
Cool, thank you for the clarification! Does this mean that standalone Nats is getting deprecated? (feel free to close the issue if this doesn't require further action)

**Comment by jnmoyne** [comment]
No Core NATS is not deprecated, you just don't need to implement your own version of streams in your application code (using acks and dealing with all the corner cases) you should simply just use JetStream instead. JetStream is just added functionality on top of Core NATS and only needs to be enabled at the nats-server level.

**Comment by mihaitodor** [comment]
Got it, thank you!
